services:
  mediamtx:
    image: bluenviron/mediamtx
    container_name: mediamtx
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=192.168.x.x
      - MTX_AUTHMETHOD=http
      - MTX_AUTHHTTPADDRESS=http://localhost:3000/api/v1/validate-stream-auth
    volumes:
      - $PWD/mediamtx.yml:/mediamtx.yml
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
    restart: unless-stopped
    network_mode: "host"
